# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  lib-coro_diff = {
    pname = "lib-coro_diff";
    version = "ba097ce3831ae9830eb4027ea1b99b1962b8e3dc";
    src = fetchgit {
      url = "https://github.com/guldoman/lite-xl-coro_diff";
      rev = "ba097ce3831ae9830eb4027ea1b99b1962b8e3dc";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Xp8MCAV9NkfEHK9g9/9WOkGPmJfxl7H5YmJt2ojvfR4=";
    };
    date = "2025-05-29";
  };
  lib-encoding = {
    pname = "lib-encoding";
    version = "v1.1";
    src = fetchFromGitHub {
      owner = "jgmdev";
      repo = "lite-xl-encoding";
      rev = "v1.1";
      fetchSubmodules = false;
      sha256 = "sha256-fN1f0IXmJoZwXXlRixc1wpZsXgRsQXBNypDJUW+UEjY=";
    };
  };
  lib-json = {
    pname = "lib-json";
    version = "v0.1.2";
    src = fetchFromGitHub {
      owner = "rxi";
      repo = "json.lua";
      rev = "v0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-JSKMxF5NSHW3QaELFPWm1sx7kHmOXEPsUkM3i/px7Gk=";
    };
  };
  lib-lsp-servers = {
    pname = "lib-lsp-servers";
    version = "6eea7cf124baad8e7abad6e388c7a16f6f6a98f2";
    src = fetchgit {
      url = "https://github.com/lite-xl/lite-xl-lsp-servers";
      rev = "6eea7cf124baad8e7abad6e388c7a16f6f6a98f2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-rKhltQ9uGnT5PJPmotxMxQm6xNO9y14klCdae8aNXcU=";
    };
    date = "2025-05-01";
  };
  lib-net = {
    pname = "lib-net";
    version = "v1.1";
    src = fetchFromGitHub {
      owner = "jgmdev";
      repo = "lite-xl-net";
      rev = "v1.1";
      fetchSubmodules = false;
      sha256 = "sha256-hWdYSmDAS8R3/pOziTryYna6RWGS53vN5rOcYvjleAI=";
    };
  };
  lib-threads = {
    pname = "lib-threads";
    version = "v1.3";
    src = fetchFromGitHub {
      owner = "jgmdev";
      repo = "lite-xl-threads";
      rev = "v1.3";
      fetchSubmodules = false;
      sha256 = "sha256-iAIJhNe/oli+DBZSGJLOCcRpOtmuWeV+unq4U2PK8a4=";
    };
  };
  lib-tree_sitter = {
    pname = "lib-tree_sitter";
    version = "06ea92e162807e3b2f9f8bec42492e349028ab13";
    src = fetchgit {
      url = "https://github.com/Evergreen-lxl/lite-xl-tree-sitter";
      rev = "06ea92e162807e3b2f9f8bec42492e349028ab13";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xaaj4wAIVR6ODLsnGMcotzH5svUBRrGLo2T/SEBp1vk=";
    };
    date = "2025-05-26";
  };
  lib-widgets = {
    pname = "lib-widgets";
    version = "dcf1c8c7087638b879d5c9c835686ccd79f963ec";
    src = fetchgit {
      url = "https://github.com/lite-xl/lite-xl-widgets";
      rev = "dcf1c8c7087638b879d5c9c835686ccd79f963ec";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-6oOxJPRzDwpFh9wp20WocT3gB0wQpA3LI4IarF0hMfw=";
    };
    date = "2025-01-27";
  };
  lite-xl-plugins = {
    pname = "lite-xl-plugins";
    version = "43fe593063903000c02e5e72d8d1d2df9331a207";
    src = fetchgit {
      url = "https://github.com/lite-xl/lite-xl-plugins";
      rev = "43fe593063903000c02e5e72d8d1d2df9331a207";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-t1RhcK0/CvcXNZ0XmGywp10ivRHgak/UX8mfHUVQ1Ak=";
    };
    date = "2025-06-19";
  };
  plg-container = {
    pname = "plg-container";
    version = "ae4eddc3f3fa1a0db56344b3b6db0ec0f2283880";
    src = fetchgit {
      url = "https://github.com/FilBot3/lite-xl-language-containerfile";
      rev = "ae4eddc3f3fa1a0db56344b3b6db0ec0f2283880";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YbwF5O2QrSrBeYzrkMCgIVIY83ULpKM8CygoiigUJj8=";
    };
    date = "2023-10-17";
  };
  plg-crystal = {
    pname = "plg-crystal";
    version = "9514ec08d0bd3aa5d3bcbf8307c4bf5a46ef1a94";
    src = fetchgit {
      url = "https://github.com/Tamnac/lite-plugin-crystal";
      rev = "9514ec08d0bd3aa5d3bcbf8307c4bf5a46ef1a94";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-JLkk4z2FaDDyZhiCz9AkQ0Ac7dltDgfB0yEqIu6/h5U=";
    };
    date = "2023-02-12";
  };
  plg-ksy = {
    pname = "plg-ksy";
    version = "8ad4bf27354ad02b9179b4a5f26f768e2208ace2";
    src = fetchgit {
      url = "https://github.com/whiteh0le/lite-plugins";
      rev = "8ad4bf27354ad02b9179b4a5f26f768e2208ace2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-d2oLmniqMVjme77OSyXbbtywmo+bIyHFn4SK1252KeY=";
    };
    date = "2020-08-18";
  };
  plg-pony = {
    pname = "plg-pony";
    version = "34d9ec673eaa6c409bcef0febaa0a36cc3acdf4e";
    src = fetchgit {
      url = "https://github.com/MrAnyx/lite-plugin-pony";
      rev = "34d9ec673eaa6c409bcef0febaa0a36cc3acdf4e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v33M1pYIh3VNzzcCYBpQ3BAu+pFJAytDd1VssEqOU1Q=";
    };
    date = "2021-08-30";
  };
  plg-vale = {
    pname = "plg-vale";
    version = "faa75f67b093978ceebc31bb7db8aa297f3c3e52";
    src = fetchgit {
      url = "https://github.com/pgmtx/lite-plugin-vale";
      rev = "faa75f67b093978ceebc31bb7db8aa297f3c3e52";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-L3lyvBEHu5BsA+7cBeEjpXWhYhQ6xb+yVBMkoPd45IQ=";
    };
    date = "2024-03-04";
  };
  plg-yuescript = {
    pname = "plg-yuescript";
    version = "0b0a68c8a2066b8270b2e85d94711c2eb033410e";
    src = fetchgit {
      url = "https://codeberg.org/pgmtx/lite-plugin-yuescript";
      rev = "0b0a68c8a2066b8270b2e85d94711c2eb033410e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-FvjIQD4a8rk8wt2R4CEXDjevrXV5SopoqVDp3tMSDw0=";
    };
    date = "2025-02-19";
  };
}
