# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  lib-coro_diff = {
    pname = "lib-coro_diff";
    version = "0.1.2";
    src = fetchgit {
      url = "https://github.com/guldoman/lite-xl-coro_diff";
      rev = "0.1.2";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-Xp8MCAV9NkfEHK9g9/9WOkGPmJfxl7H5YmJt2ojvfR4=";
    };
  };
  lib-encoding = {
    pname = "lib-encoding";
    version = "v1.1";
    src = fetchFromGitHub {
      owner = "jgmdev";
      repo = "lite-xl-encoding";
      rev = "v1.1";
      fetchSubmodules = false;
      sha256 = "sha256-fN1f0IXmJoZwXXlRixc1wpZsXgRsQXBNypDJUW+UEjY=";
    };
  };
  lib-json = {
    pname = "lib-json";
    version = "v0.1.2";
    src = fetchFromGitHub {
      owner = "rxi";
      repo = "json.lua";
      rev = "v0.1.2";
      fetchSubmodules = false;
      sha256 = "sha256-JSKMxF5NSHW3QaELFPWm1sx7kHmOXEPsUkM3i/px7Gk=";
    };
  };
  lib-lsp-servers = {
    pname = "lib-lsp-servers";
    version = "443a076fe5741dbd3a8f774c9b577bbf4c58f4e9";
    src = fetchgit {
      url = "https://github.com/lite-xl/lite-xl-lsp-servers";
      rev = "443a076fe5741dbd3a8f774c9b577bbf4c58f4e9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-BVzNbZaw0xbfzF+ULffurh9j3b/okx95Lcdq2r8IqLc=";
    };
    date = "2025-08-04";
  };
  lib-net = {
    pname = "lib-net";
    version = "v1.1";
    src = fetchFromGitHub {
      owner = "jgmdev";
      repo = "lite-xl-net";
      rev = "v1.1";
      fetchSubmodules = false;
      sha256 = "sha256-hWdYSmDAS8R3/pOziTryYna6RWGS53vN5rOcYvjleAI=";
    };
  };
  lib-threads = {
    pname = "lib-threads";
    version = "v1.3";
    src = fetchFromGitHub {
      owner = "jgmdev";
      repo = "lite-xl-threads";
      rev = "v1.3";
      fetchSubmodules = false;
      sha256 = "sha256-iAIJhNe/oli+DBZSGJLOCcRpOtmuWeV+unq4U2PK8a4=";
    };
  };
  lib-tree_sitter = {
    pname = "lib-tree_sitter";
    version = "v0.1.2";
    src = fetchgit {
      url = "https://github.com/Evergreen-lxl/lite-xl-tree-sitter";
      rev = "v0.1.2";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-xaaj4wAIVR6ODLsnGMcotzH5svUBRrGLo2T/SEBp1vk=";
    };
  };
  lib-widgets = {
    pname = "lib-widgets";
    version = "dcf1c8c7087638b879d5c9c835686ccd79f963ec";
    src = fetchgit {
      url = "https://github.com/lite-xl/lite-xl-widgets";
      rev = "dcf1c8c7087638b879d5c9c835686ccd79f963ec";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-6oOxJPRzDwpFh9wp20WocT3gB0wQpA3LI4IarF0hMfw=";
    };
    date = "2025-01-27";
  };
  lite-xl-plugins = {
    pname = "lite-xl-plugins";
    version = "1c531032a5aa9c1efcc32aa239171083a036db07";
    src = fetchgit {
      url = "https://github.com/lite-xl/lite-xl-plugins";
      rev = "1c531032a5aa9c1efcc32aa239171083a036db07";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XZalWbpenF5GRG0luhCae6Kulg+115+QPUspReuSxEc=";
    };
    date = "2025-08-28";
  };
  plg-container = {
    pname = "plg-container";
    version = "ae4eddc3f3fa1a0db56344b3b6db0ec0f2283880";
    src = fetchgit {
      url = "https://github.com/FilBot3/lite-xl-language-containerfile";
      rev = "ae4eddc3f3fa1a0db56344b3b6db0ec0f2283880";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-YbwF5O2QrSrBeYzrkMCgIVIY83ULpKM8CygoiigUJj8=";
    };
  };
  plg-crystal = {
    pname = "plg-crystal";
    version = "9514ec08d0bd3aa5d3bcbf8307c4bf5a46ef1a94";
    src = fetchgit {
      url = "https://github.com/Tamnac/lite-plugin-crystal";
      rev = "9514ec08d0bd3aa5d3bcbf8307c4bf5a46ef1a94";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-JLkk4z2FaDDyZhiCz9AkQ0Ac7dltDgfB0yEqIu6/h5U=";
    };
  };
  plg-devicons = {
    pname = "plg-devicons";
    version = "85355aa80546e78a841c3d9ce32bcdf77b0fa01a";
    src = fetchgit {
      url = "https://github.com/PerilousBooklet/lite-xl-devicons";
      rev = "85355aa80546e78a841c3d9ce32bcdf77b0fa01a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-AS+vfcLxk+nfQ+yIbr39+rCpA9bmNYNQFddHXJvp+lE=";
    };
    date = "2025-05-24";
  };
  plg-discord-presence = {
    pname = "plg-discord-presence";
    version = "v0.2";
    src = fetchFromGitHub {
      owner = "vincens2005";
      repo = "lite-xl-discord2";
      rev = "v0.2";
      fetchSubmodules = false;
      sha256 = "sha256-ZUu+8LVo+jtOrjuz1MUZ8kt3JpnWkz7fwX8dJLmHHVs=";
    };
  };
  plg-evg-c = {
    pname = "plg-evg-c";
    version = "7fa1be1b694b6e763686793d97da01f36a0e5c12";
    src = fetchgit {
      url = "https://github.com/tree-sitter/tree-sitter-c";
      rev = "7fa1be1b694b6e763686793d97da01f36a0e5c12";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-gmzbdwvrKSo6C1fqTJFGxy8x0+T+vUTswm7F5sojzKc=";
    };
  };
  plg-evg-cpp = {
    pname = "plg-evg-cpp";
    version = "56455f4245baf4ea4e0881c5169de69d7edd5ae7";
    src = fetchgit {
      url = "https://github.com/tree-sitter/tree-sitter-cpp";
      rev = "56455f4245baf4ea4e0881c5169de69d7edd5ae7";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-yU1bwDhwcqeKrho0bo4qclqDDm1EuZWHENI2PNYnxVs=";
    };
  };
  plg-evg-css = {
    pname = "plg-evg-css";
    version = "6e327db434fec0ee90f006697782e43ec855adf5";
    src = fetchgit {
      url = "https://github.com/tree-sitter/tree-sitter-css";
      rev = "6e327db434fec0ee90f006697782e43ec855adf5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-en379DlqzzvQNvKgE8CtiA00j7phUyipttqbnETGHKc=";
    };
  };
  plg-evg-d = {
    pname = "plg-evg-d";
    version = "45e5f1e9d6de2c68591bc8e5ec662cf18e950b4a";
    src = fetchgit {
      url = "https://github.com/gdamore/tree-sitter-d";
      rev = "45e5f1e9d6de2c68591bc8e5ec662cf18e950b4a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-q96RgJWrMop2HBBsQloVTspe3EaMtUL3wmVuT9xnE/g=";
    };
  };
  plg-evg-go = {
    pname = "plg-evg-go";
    version = "5e73f476efafe5c768eda19bbe877f188ded6144";
    src = fetchgit {
      url = "https://github.com/tree-sitter/tree-sitter-go";
      rev = "5e73f476efafe5c768eda19bbe877f188ded6144";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PgFdtkPMgkNK7Gv6dBf89lNjJrZyt9Wp5h5OIwd83aw=";
    };
  };
  plg-evg-gomod = {
    pname = "plg-evg-gomod";
    version = "6efb59652d30e0e9cd5f3b3a669afd6f1a926d3c";
    src = fetchgit {
      url = "https://github.com/camdencheek/tree-sitter-go-mod";
      rev = "6efb59652d30e0e9cd5f3b3a669afd6f1a926d3c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-KD6Fio9qie3wbGAvQaYsMdYOK1QjnRrGExt1oL/6mis=";
    };
  };
  plg-evg-gosum = {
    pname = "plg-evg-gosum";
    version = "e2ac513b2240c7ff1069ae33b2df29ce90777c11";
    src = fetchgit {
      url = "https://github.com/amaanq/tree-sitter-go-sum";
      rev = "e2ac513b2240c7ff1069ae33b2df29ce90777c11";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-2foA2sd5PQpmeX8OhXrW/dxoJaEyxDXzPWh+UD0dgzQ=";
    };
  };
  plg-evg-html = {
    pname = "plg-evg-html";
    version = "cbb91a0ff3621245e890d1c50cc811bffb77a26b";
    src = fetchgit {
      url = "https://github.com/tree-sitter/tree-sitter-html";
      rev = "cbb91a0ff3621245e890d1c50cc811bffb77a26b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lNMiSDAQ49QpeyD1RzkIIUeRWdp2Wrv6+XQZdZ40c1g=";
    };
  };
  plg-evg-javascript = {
    pname = "plg-evg-javascript";
    version = "6fbef40512dcd9f0a61ce03a4c9ae7597b36ab5c";
    src = fetchgit {
      url = "https://github.com/tree-sitter/tree-sitter-javascript";
      rev = "6fbef40512dcd9f0a61ce03a4c9ae7597b36ab5c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-X9DDCBF+gQYL0syfqgKVFvzoy2tnBl+veaYi7bUuRms=";
    };
  };
  plg-evg-julia = {
    pname = "plg-evg-julia";
    version = "18b739c1563c83fc816170a4241adfa4b69e5c47";
    src = fetchgit {
      url = "https://github.com/tree-sitter/tree-sitter-julia";
      rev = "18b739c1563c83fc816170a4241adfa4b69e5c47";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-DLzbu/r+CNQinHDoy4IihHHbr/j+WDMfimn03gWNO5s=";
    };
  };
  plg-evg-lua = {
    pname = "plg-evg-lua";
    version = "4fbec840c34149b7d5fe10097c93a320ee4af053";
    src = fetchgit {
      url = "https://github.com/MunifTanjim/tree-sitter-lua";
      rev = "4fbec840c34149b7d5fe10097c93a320ee4af053";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-fO8XqlauYiPR0KaFzlAzvkrYXgEsiSzlB3xYzUpcbrs=";
    };
  };
  plg-evg-rust = {
    pname = "plg-evg-rust";
    version = "3691201b01cacb2f96ffca4c632c4e938bfacd88";
    src = fetchgit {
      url = "https://github.com/tree-sitter/tree-sitter-rust";
      rev = "3691201b01cacb2f96ffca4c632c4e938bfacd88";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-a9Te7SXVd7hkinrpvwrWgb6J53PoSL/Irk0DpQ6vS7k=";
    };
  };
  plg-evg-zig = {
    pname = "plg-evg-zig";
    version = "a80a6e9be81b33b182ce6305ae4ea28e29211bd5";
    src = fetchgit {
      url = "https://github.com/maxxnino/tree-sitter-zig";
      rev = "a80a6e9be81b33b182ce6305ae4ea28e29211bd5";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-o3RAbW8kLSfKxuQ/z7WDb5BaDVxZUG5oFutovRkErjk=";
    };
  };
  plg-fallbackfonts = {
    pname = "plg-fallbackfonts";
    version = "281cafc014f7931f041046f76496797695678bb4";
    src = fetchgit {
      url = "https://github.com/takase1121/lite-fallback-fonts";
      rev = "281cafc014f7931f041046f76496797695678bb4";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-zkgysv+pat+FjMmubb573gsQ3PLb+Y9oM81bH45cxwA=";
    };
    date = "2021-02-17";
  };
  plg-formatters = {
    pname = "plg-formatters";
    version = "3607237661cde34a983372f173dcc46c4f122fb6";
    src = fetchgit {
      url = "https://github.com/vincens2005/lite-formatters";
      rev = "3607237661cde34a983372f173dcc46c4f122fb6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-u7yrgkl3UgCN90iiKgQ811B9Ox6SU3mK51bxxEniUMw=";
    };
    date = "2025-07-06";
  };
  plg-ksy = {
    pname = "plg-ksy";
    version = "8ad4bf27354ad02b9179b4a5f26f768e2208ace2";
    src = fetchgit {
      url = "https://github.com/whiteh0le/lite-plugins";
      rev = "8ad4bf27354ad02b9179b4a5f26f768e2208ace2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-d2oLmniqMVjme77OSyXbbtywmo+bIyHFn4SK1252KeY=";
    };
  };
  plg-litepresence = {
    pname = "plg-litepresence";
    version = "v0.3.0";
    src = fetchFromGitHub {
      owner = "sammy-ette";
      repo = "litepresence";
      rev = "v0.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-x3kGkPGXEjjo+PKMevqJyeuIRIzgw8XRfQr4spTeFkE=";
    };
  };
  plg-pony = {
    pname = "plg-pony";
    version = "34d9ec673eaa6c409bcef0febaa0a36cc3acdf4e";
    src = fetchgit {
      url = "https://github.com/MrAnyx/lite-plugin-pony";
      rev = "34d9ec673eaa6c409bcef0febaa0a36cc3acdf4e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v33M1pYIh3VNzzcCYBpQ3BAu+pFJAytDd1VssEqOU1Q=";
    };
  };
  plg-quetta = {
    pname = "plg-quetta";
    version = "adee96d383776bd97acea76d612bd959cfd10b86";
    src = fetchgit {
      url = "https://github.com/adamharrison/quetta";
      rev = "adee96d383776bd97acea76d612bd959cfd10b86";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-+WDwnUlg+jHSdRByTOB+cULnzNgZIqFs5whgZGu3ze8=";
    };
    date = "2024-09-29";
  };
  plg-terminal = {
    pname = "plg-terminal";
    version = "809454f5f7ca421842b2b2b4d3ebf80da2767c54";
    src = fetchgit {
      url = "https://github.com/adamharrison/lite-xl-terminal";
      rev = "809454f5f7ca421842b2b2b4d3ebf80da2767c54";
      fetchSubmodules = true;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-iV7fICJRs1rgeOIK08wQqPzned/dGJ6aeOVDUpi+GII=";
    };
    date = "2025-10-03";
  };
  plg-vale = {
    pname = "plg-vale";
    version = "faa75f67b093978ceebc31bb7db8aa297f3c3e52";
    src = fetchgit {
      url = "https://github.com/pgmtx/lite-plugin-vale";
      rev = "faa75f67b093978ceebc31bb7db8aa297f3c3e52";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-L3lyvBEHu5BsA+7cBeEjpXWhYhQ6xb+yVBMkoPd45IQ=";
    };
  };
  plg-yuescript = {
    pname = "plg-yuescript";
    version = "0b0a68c8a2066b8270b2e85d94711c2eb033410e";
    src = fetchgit {
      url = "https://codeberg.org/pgmtx/lite-plugin-yuescript";
      rev = "0b0a68c8a2066b8270b2e85d94711c2eb033410e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-FvjIQD4a8rk8wt2R4CEXDjevrXV5SopoqVDp3tMSDw0=";
    };
  };
}
