# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  lite-xl-plugins = {
    pname = "lite-xl-plugins";
    version = "43fe593063903000c02e5e72d8d1d2df9331a207";
    src = fetchgit {
      url = "https://github.com/lite-xl/lite-xl-plugins";
      rev = "43fe593063903000c02e5e72d8d1d2df9331a207";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-t1RhcK0/CvcXNZ0XmGywp10ivRHgak/UX8mfHUVQ1Ak=";
    };
    date = "2025-06-19";
  };
}
