{ lib, ... }:
let
  inherit (lib) genPluginPaths subImport;

  # lite-xl-plugins
  pluginFiles = [
    "align_carets"
    "autoinsert"
    "autosave"
    "autosaveonfocuslost"
    "autowrap"
    "bigclock"
    "bracketmatch"
    "centerdoc"
    "cleanstart"
    "colorpicker"
    "colorpreview"
    "copyfilelocation"
    "custom_caret"
    "datetimestamps"
    "dragdropselected"
    "ephemeral_tabs"
    "eval"
    "exec"
    "extend_selection_line"
    "fontconfig"
    "fontpreview"
    "force_syntax"
    "ghmarkdown"
    "gitopen"
    "gitstatus"
    "gofmt"
    "gui_filepicker"
    "indent_convert"
    "indentguide"
    "ipc"
    "keymap_export"
    "lfautoinsert"
    "linenumbers"
    "lite-debugger"
    "macmodkeys"
    "markers"
    "memoryusage"
    "minimap"
    "motiontrail"
    "navigate"
    "nerdicons"
    "nonicons"
    "opacity"
    "open_ext"
    "openfilelocation"
    "openselected"
    "pdfview"
    "primary_selection"
    "rainbowparen"
    "regexreplacepreview"
    "restoretabs"
    "scalestatus"
    "search_ui"
    "select_colorscheme"
    "selectionhighlight"
    "settings"
    "smallclock"
    "smartopenselected"
    "smoothcaret"
    "sort"
    "spellcheck"
    "sticky_scroll"
    "su_save"
    "svg_screenshot"
    "tab_switcher"
    "tabnumbers"
    "tetris"
    "texcompile"
    "titlesize"
    "togglesnakecamel"
    "typingspeed"
    "unboundedscroll"
    "wordcount"
  ];

  pluginDirs = [ "editorconfig" "profile" ];

  pluginPaths = genPluginPaths "${lib.NXLPkgs.lxl}/plugins/" pluginFiles pluginDirs (subImport ./external.nix);
in
pluginPaths

